### ISSUE TITLE
Fix typo in Docker/Dockerfile

### ISSUE THREAD

**Issue by jdev-homeauto** [evanrich/py-eagle-mqtt#11]
File Docker/Dockerfile contains a typo in the base image - "alpine" is written "apline". Correcting this typo would allow me to use docker-compose to build the image direct from github. I have created a [pull request](https://github.com/evanrich/py-eagle-mqtt/pull/10) with this small change.

**Comment by evanrich** [comment]
I'm so sorry for getting back to you late on this, my job has been a hassle lately, haven't had a lot of free time.  Merged, and thank you!
