### ISSUE TITLE
MQTT_PASSWORD is the wrong environment parameter

### ISSUE THREAD

**Issue by cwmccann** [evanrich/py-eagle-mqtt#8]
Hi,

I was trying to connect to a MQTT server using that required a username and password.  After a bunch of troubleshooting I discovered that MQTT_PASSWORD should be MQTT_PASS as defined in py-eagle-mqtt/Docker/src/conf/broker.py line 21.

Either the broker.py should be updated to read the environment variable MQTT_PASSWORD or the documentation should be updated.  I'd be happy to create a pull request if you indicate which way you want to go.

**Comment by evanrich** [comment]
Agreed.  I merged your PR, thanks for catching this!
